INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('VS650', 'Corsair', '69', '5', 'corsairVS650.jpg', '8');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('RM750x', 'Corsair', '135', '5', 'corsairRM750x.jpg', '8');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('SuperNOVA G2', 'EVGA', '118', '5', 'evgaSuperNOVAG2.jpg', '8');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Crystal 460X RGB', 'Corsair', '179', '5', 'corsairCrystal460XRGB.jpg', '7');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Define R5 Black', 'Fractal', '119', '5', 'fractalDefineR5Black.jpg', '7');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Source 340 Elite', 'NZXT', '119', '5', 'nzxtSource340Elite.jpg', '7');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Geforce GTX 1050 Ti OC 4G', 'Gigabyte', '160', '5', 'gigabyteGeforceGTX1050Ti.jpg', '6');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Geforce GTX 1070 GAMING X 8G', 'MSI', '459', '5', 'msiGeforceGTX1070GAMINGX.jpg', '6');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Geforce GTX 1080 Ti STRIX 11G', 'Asus', '869', '5', 'asusGeforceGTX1080Ti.jpg', '6');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Black 2To', 'Western Digital', '137', '5', 'westernDigitalBlack2To.jpg', '5');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Red Pro 4To', 'Western Digital', '242', '5', 'westernDigitalRedPro4To.jpg', '5');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Barracuda', 'Seagate', '132', '5', 'seagateBarracuda4To.jpg', '5');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Fury 2x8Go', 'HyperX', '160', '5', 'hyperXFury2x8.jpg', '4');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Vengeance LPX 2x8Go', 'Corsair', '150', '5', 'corsairVengeanceLPX2x8.jpg', '4');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Ripjaws V 2x16', 'G.Skill', '285', '5', 'g.skillRipjawsV2x16.jpg', '4');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('STRIX Z270F GAMING', 'Asus', '196', '5', 'asusSTRIXZ270GAMING.jpg', '3');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Z170XP-SLI', 'Gigabyte', '169', '5', 'gigabyteZ170XP-SLI.jpg', '3');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Z270 Gaming Pro Carbon', 'MSI', '183', '5', 'msiZ270GamingProCarbon.jpg', '3');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('H100i v2', 'Corsair', '139', '5', 'corsairH100iv2.jpg', '2');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Dark Rock 3', 'Be Quiet !', '79', '5', 'beQuietDarkRock3.jpg', '2');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Dark Rock 3 PRO', 'Be Quiet !', '89', '5', 'beQuietDarkRockPRO3.jpg', '2');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Core i7 7700K BOX 4.2GHz', 'Intel', '365', '5', 'intelCorei77700KBOX.jpg', '1');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Core i5 7600K BOX 3.8GHz', 'Intel', '256', '5', 'intelCorei57600KBOX.jpg', '1');
INSERT INTO `gestockdb`.`products` (`name`, `brand`, `price`, `alertQuantity`, `imgName`, `idCategory_fk`) VALUES ('Pentium G4560 3.5GHz', 'Intel', '74.60', '5', 'intelPentiumG4560.jpg', '1');